Add playbook for checking for expired certificates on an ubuntu server
Osirium/ppa-playbooks pull request #25
Opened 2020-10-05 14:57 UTC by NeilGerring

This adds a new playbook for checking for any expired/expiring certificates on an ubuntu server.

2020-10-06 13:54 UTC, edwardzsmith commented on ssh/check-for-expired-certificates/README.md
> +This is an interactive task for auditing & resetting disconnected RDP sessions on a Windows Server.
Is this the correct description?

2020-10-06 13:54 UTC, edwardzsmith commented on ssh/check-for-expired-certificates/README.md
> +- The Ubuntu Server control account must be part of the sudoers group.
Inconsistent use of the full stop :(

2020-10-06 13:55 UTC, edwardzsmith commented on ssh/check-for-expired-certificates/README.md
> +- Choose to check for certificates expiring in the near future by selecting one of the following:
Was does it do after this? does it display the expired certs in some way?

2020-10-06 13:57 UTC, edwardzsmith commented on ssh/check-for-expired-certificates/check-for-expired-certificates.yml
> +            This task finds Ubuntu Server devices provisioned on your PAM Platform, and looks for expired/due to expire x509 certificates on your selected device of interest.
Can you select multiple devices to check? This implies that you can...

2020-10-06 13:59 UTC, edwardzsmith commented
This looks like the sort of thing that you might want to schedule, and get it to email you a report. But let's not bother with that right now, unless you are super keen

2020-10-06 14:49 UTC, tomguyatt requested changes

2020-10-06 14:49 UTC, tomguyatt commented on index.json
> +      "path": "ssh/check-for-expired-certificates",
If this is specific to Ubuntu, we should make an Ubuntu folder for it.

2020-10-06 14:49 UTC, tomguyatt commented on ssh/check-for-expired-certificates/README.md
> +This task will use the selected Ubuntu Server device's control account to make the connection.
Any special permissions required?

2020-10-06 14:49 UTC, tomguyatt commented on ssh/check-for-expired-certificates/check-for-expired-certificates.yml
> +          value: ubuntu_device.0
You can also use...

```YAML
- ppa_tools.lists.get_first_item:
  load:
    items: ubuntu_devices
  save: ubuntu_device
```

...which is just as many lines, but a bit more self-explanatory.

2020-10-06 14:49 UTC, tomguyatt commented on ssh/check-for-expired-certificates/check-for-expired-certificates.yml
> +        save: all_certificates
You can use the [split_text](https://osirium.com/documentation/ppa/tasks/playbooks/builtin_actions/#split_text) built-in here:

```YAML
- split_text:
    delimiter: "\n"
  load:
    text: all_certificates
  save: all_certificates
```

2020-10-06 14:49 UTC, tomguyatt commented on ssh/check-for-expired-certificates/check-for-expired-certificates.yml
> +          percent: 100
You could drop this into the end of the previous step and only display it when `loop.step.item.index + 1` is equal to the number of certificates being checked.

That would allow you to use the  `len(expired_certs) > 0` when condition once on the final step itself, rather than 2 actions.

2020-10-07 09:35 UTC, NeilGerring commented on index.json
> +      "path": "ssh/check-for-expired-certificates",
https://github.com/Osirium/ppa-playbooks/pull/25/commits/330e82597e3df656f8add8a3e05497278c981568

2020-10-07 09:36 UTC, NeilGerring commented on ssh/check-for-expired-certificates/check-for-expired-certificates.yml
> +        save: all_certificates
I had to use the ppa_tools.text.split_lines here but much better then the eval

2020-10-07 10:22 UTC, tomguyatt approved these changes

2020-10-07 10:22 UTC, merged